version: "2"
services:
  prod:
    build:
      context: .
      dockerfile: Dockerfile
    image: aldryn/base-experimental:py3-latest-slim-stretch
    volumes:
      - "./stack:/stack"

  dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TARGET: dev
    image: aldryn/base-experimental:py3-latest-slim-stretch-dev
    volumes:
      - "./stack:/stack"
